# Оферы
## Получить список офнров
GET http://localhost:6000/offers HTTP/1.1
Content-Type: application/json

###
## Добавить новую категорию
POST http://localhost:6000/offers HTTP/1.1
Content-Type: application/json

###
